## Default test configuration (override via test-<profile>.properties or env vars)

# Base URL of the API under test
base.url=https://api.salla.dev
base.url.admin=https://api.salla.dev/admin/v2
base.url.store=https://api.salla.dev/store/v1

# Default bearer tokens (examples — replace in your environment)
API_TOKEN=
store_customer_token=
finance_manager_token=
designer_manager_token=
technical_manager_token=
marketing_manager_token=
products_manager_token=
orders_manager_token=
general_manager_token=Bearer v4.public.eyJ1c2VyIjoxNjk1MTQ1MjMxLCJzdG9yZSI6MTMyODg0MjM1OSwidmVyaWZpZWQiOnRydWUsInNvdXJjZSI6ImRhc2hib2FyZCIsImZpbmdlcnByaW50IjoiMDdlYzE2ZGM0ZWVhZGYxYzYwNDY4NDc2MzgwYjA5OGM4NGI3MjgxYTVhM2E2NDM2YTVkYjAwN2Q1YzUzNTJlYyIsImVtYWlsIjoiamFsbWF0YXJpQGdtYWlsLmNvbSIsIm93bmVyIjoxNTEyNTE3OTIyLCJpcCI6IjEzOC4xOTkuMTQ4LjI1MSIsImZ0IjoibXMiLCJpc3MiOiJzYWxsYSIsImF1ZCI6InNhbGxhIiwiaWF0IjoiMjAyNS0xMC0wMlQxNDoyNDo1MiswMzowMCIsIm5iZiI6IjIwMjUtMTAtMDJUMTQ6MjQ6NTIrMDM6MDAiLCJleHAiOiIyMDI1LTEwLTE2VDE0OjI0OjUyKzAzOjAwIn0XUve9MWtesVeNDvwWiySqkhLiaasrD0W1MlwXcuwCvxJBDbFNJTNonUy2UV-WAlHKDDyjoV57MKGExKjt1SoF
employee_token=
merchent_token=
API_TOKEN_GUEST=
